name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: SonarCloud Scan
  uses: SonarSource/sonarqube-scan-action@v5.0.0
  with:
    args: >
      -Dsonar.organization=dizza19
      -Dsonar.projectKey=frontend-project-11
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
